### ISSUE TITLE
addEventListener

### ISSUE THREAD

**Issue by nativeB** [mongodb-js/charts-embed-sdk#32]
**Describe the bug**
click events have been documented here https://docs.mongodb.com/charts/saas/handle-click-events/ but  the addEventListener  method does not exist

**To Reproduce**
chart.render(document.getElementById("chart")).then(
     () => chart.addEventListener('click',
       (payload) => alert(JSON.stringify(payload)),
       options)
   );

**Expected behavior**
be able to add a click event to chart

**Desktop (please complete the following information):**
 -browser chrome

**Additional context**
same issues on  UMD version and npm

**Comment by kristinamongo** [comment]
Hello @nativeB. I assume you figured out why you were not finding the method `addEventListener` but I will post it here in case anyone else has the same issue and is looking at this. The method is only available in our beta version (currently -  v2.1.0-beta.1) because it is part of set of features we will release in a new version once they are all implemented - most probably in the next month or two.
